version: '3'

services:

  oneline-backend:
    build: ./
    ports:
      - 8080:8080
    volumes:
      - ./src:/home/node/oneline-backend
    environment:
      - EXPOSED_PORT=8080
    external_links:
      - oneline-backend
    depends_on:
      - mysql
  mysql:
    build: ./mysql-db
    ports:
      - 4242:4242
    restart: always
    volumes:
      - ./mysql-db/data/mysqldata:/var/lib/mysql/data
      - ./mysql/data/seed.sql:/docker-entrypoint-initdb.d/aa-seed.sql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: oneline-db