version: '3'

services:

  oneline-backend:
    build: ./
    ports:
      - 4242:4242
    volumes:
      - ./:/home/node/src/oneline-backend
    environment:
      - EXPOSED_PORT=4242
    external_links:
      - oneline-backend
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    restart: always
    volumes:
    - ./mariadb-data/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: oneline-db
